#!/bin/bash

LOAD=(`uptime | sed -s 's/,//g'`)
if [ ${LOAD[8]/./} -gt 100 ]; then
	echo "<h3><font color=red><B>System load is high (${LOAD[8]/./}%)!</B></FONT></H3>"
fi

L=`ls ~olypen/lck`
if [ ! -z "$L" ]; then
	echo "<H3><font color=red><B>The following services are off: ${L//.lck/}.</B></FONT></H3>"
fi

LCK="/var/lock/daily.lck"
if [ -f $LCK ]; then
	echo "<h3><font color=red><B>Daily backup in progress since $(stat -c '%z' $LCK | cut -c1-16), please wait.</B></FONT></H3>"
	echo "Navbar will be enabled when backup is complete."
	exit
fi

LIST=$(cat $0.conf | grep -v '^#')
echo "<H3 style='background-color: darkblue; color=white; text-align: left'>&nbsp;<b><i>$1</i></b><br>&nbsp;"
for i in $LIST; do
	A=$(echo "$i" | cut -f1 -d:)
	B=$(echo "$i" | cut -f2 -d:)
	if [ "$2" = "$A" ]; then
		echo "&nbsp;<B style='background-color: white; color=darkblue'>&nbsp;$A&nbsp;</B>&nbsp;"
	else
		echo "&nbsp;<a href='$B' style='background-color: lightgrey; text-decoration: none; color=darkblue;'>&nbsp;$A&nbsp;</A>&nbsp;"
	fi
done
echo "</H1>"
