#!/bin/bash

WS_OPTS="--quiet --append-output=$HOME/log/websphere.log --output-document=$HOME/log/websphere.out --timeout=5 --tries=10"
url="http://joey.pnl.gov/gtWeb/MarketClearance"
mkt=$(( $(date +'%s')/300 ))

avg=50
std=10

if [ -z "$1" ]; then
	echo "Syntax: $(basename $0) [hour|minute|flat]"
	exit 1
elif [ "$1" == "hour" ]; then
	H=$(date +'%k')
	D=$(( $H % 7 - 3))
	# hourly price saw tooth
	LASTCLEAR="msgtype=marketclear&posttime=$(date +'%Y-%m-%d%%20%H%%3a%M%%3a%S')&quantity=100&price=$(($avg+$std*$D))&avg24=$avg&std24=$std&avg168=$avg&std168=$std&mkt_id=$mkt"
elif [ "$1" == "minute" ]; then
	M=$(date +'%M')
	D=$(( ($M/5) % 7 - 3))
	LASTCLEAR="msgtype=marketclear&posttime=$(date +'%Y-%m-%d%%20%H%%3a%M%%3a%S')&quantity=100&price=$(($avg+$std*$D))&avg24=$avg&std24=$std&avg168=$avg&std168=$std&mkt_id=$mkt"
elif [ "$1" == "flat" ]; then
	# constant price
	LASTCLEAR="msgtype=marketclear&posttime=$(date +'%Y-%m-%d%%20%H%%3a%M%%3a%S')&quantity=100&price=$avg&avg24=$avg&std24=$std&avg168=$avg&std168=$std&mkt_id=$mkt"
elif [ "$1" == "random" ]; then
	D=0
	LASTCLEAR="msgtype=marketclear&posttime=$(date +'%Y-%m-%d%%20%H%%3a%M%%3a%S')&quantity=100&price=$(($avg+$std*$D))&avg24=$avg&std24=$std&avg168=$avg&std168=$std&mkt_id=$mkt"
else
	echo "$(basename $0): '$1' is not valid"
	exit 1
fi

if [ ! "$2" == "test" ]; then
	wget $WS_OPTS "$url?$LASTCLEAR" || exit 1
else
	echo $LASTCLEAR
fi
exit 0
